name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get install -y ninja-build lld

      - run: sudo bash build.sh

      - uses: actions/upload-artifact@v3
        with:
            name: bin
            path: ${{ github.workspace }}/llvm-project/web-build/bin/
