name: build

on:
  push:
    branches: [ "main" ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

#       - uses: actions/cache@v3
#         with:
#           path: /tmp/ccache
#           key: ccache

#       - run: sudo apt-get install -y ninja-build ccache

#       - run: sudo sh build.sh

#       - uses: actions/upload-artifact@v3
#         with:
#             name: bin
#             path: ${{ github.workspace }}/web-llvm-build/bin/

      - run: gh api --method DELETE /repos/OWNER/REPO/actions/caches/CACHE_ID
