name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.16.x'

      - run: sudo bash debian_build.sh

      - uses: actions/upload-artifact@v3
        with:
            name: bin
            path: ${{ github.workspace }}/llvm-project/web-build/bin/
