name: build

on:
  push:
    branches: [ "main" ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: download ccache cache llvm-dev clang
        id: cache
        uses: actions/cache@v3
        with:
          path: /tmp/ccache
          key: ccache

      - name: install dependencies
        run: sudo apt-get install -y ninja-build ccache

      - name: build
        run: sudo sh test.sh

      - name: upload bin
        uses: actions/upload-artifact@v3
        with:
            name: bin
            path: ${{ github.workspace }}/web-llvm-build/bin/

      - name: delete ccache cache so it can be overwritten
        if: steps.cache.outputs.cache-hit == 'true'
        run: gh api --method DELETE /repos/AlistairKeiller/editor-wasm/actions/caches?key=ccache
