name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # - uses: easimon/maximize-build-space@master
      #   with:
      #     swap-size-mb: 16384

      - uses: actions/checkout@v3

      - run: sudo bash debian_build.sh

      - uses: actions/upload-artifact@v3
        with:
            name: bin
            path: ${{ github.workspace }}/llvm-project/web-build/bin/
